config/routes.rb
Rails.application.routes.draw do
    
    get '/sup_home', to: 'supervisors#home', as: :sup_home
    get '/facebook', to: 'social#facebook', as: :facebook
    get '/twitter', to: 'social#twitter', as: :twitter
    get '/website', to: 'social#website', as: :website
    get '/instagram', to: 'social#instagram', as: :instagram
    
    get '/secret', to: 'pages#index', as: :secret
    
    resources :users, only: [:new, :create] do
        resources :activities do
            resources :weeks
        end
    end
        
    get '/sign_up', to: 'users#new', as: :sign_up
    get '/home', to: 'users#home', as: :home
    get '/landing', to: 'users#landing', as: :landing
    root to: 'users#landing'
    
    resources :sessions, only: [:new, :create, :destroy]
    get '/log_in', to: 'sessions#new', as: :log_in
    delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/week.rb
class Week < ActiveRecord::Base
  belongs_to :activities
  belongs_to :users
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
    before_action :set_activity
    before_action :set_user
    before_action :set_week_num

    def index
        #@week_number = params[:week_num]
        @weeks = Week.all
        
        #just finding the activity id of the week
        @activity = Activity.find(params[:activity_id])
        @activity_id = params[:activity_id]
        
        #Gets the activity attributes for the week that you've selected.
        @activity_type = @activity.activity_type
        @activity_name = @activity.activity_name
        
        #Find current week object
        @week = Week.where(activities_id:@activity_id, week_num:@week_number)
        
        #For posting the status of the week's submission/approval
        @weeks.where(activities_id:@activity_id, week_num:@week_number).each do |week|
            if week.submitted==false
                @submitted = 'Not submitted'
            else
                @submitted = 'Submitted'
            end
            if week.approved==false
                @approved = 'Not approved'
            else
                @approved = 'Approved'
            end
        end 

        
    end
    
    def edit
        #@week_number = params[:week_num]
        @weeks = Week.all
        
        #just finding the activity id of the week
        @activity = Activity.find(params[:activity_id])
        @activity_id = params[:activity_id]
        @user = User.find(params[:user_id])
        
        #Gets the activity attributes for the week that you've selected.
        @activity_type = @activity.activity_type
        @activity_name = @activity.activity_name
        
        #Find current week object
        @week = Week.find(params[:id])
        
    end
    
    def update
        @week = Week.find(params[:id])
        @week_id = params[:id]
        @weeks = Week.all
        
        @weeks.where(id: @week_id).each do |week|
            @week_num = week.week_num
        end 
        
        if @week.update_attributes(week_params)
            UserMailer.update_week(@user,@activity,@week).deliver
            redirect_to user_activity_weeks_path(:user_id =>  @user_id, :activity_id => @activity_id, :activity_type => $activity_type_var, :week_num => @week_num)
        else
            render root_path
        end
    end
    
    
    def new
        #@week_number = params[:week_num]
        @week= Week.new
    end
    
    def create
        @week = Week.new(week_params)
        if @week.save
            redirect_to home_path
        else
            render root_path
        end
    end
    
    
    
    private
    
    def week_params
        params.require(:week).permit(:activities_id, :week_num, :date_completed, :submitted, :approved)
    end
    
    def set_activity
        #just finding the activity id of the week
        @activity = Activity.find(params[:activity_id])
        @activity_id = params[:activity_id]
    end
    
    def set_user
        @user = current_user
        @user_id = params[:user_id]
    end
    
    def set_week_num
        @week_number = params[:week_num]
    end
    

end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/edit.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/bootstrap' %>

    <body style="padding-top: 100px;">

        <%= render 'layouts/header' %>

            <div>

                <!-- Rendering the Type of Activity -->
                <% if $activity_type_var == 1 %>
                    <h1><%= "Personal Activity" %></h1>

                <% elsif $activity_type_var == 2 %>
                        <h1> <%= "Physical Activity" %> </h1>

                <% elsif $activity_type_var == 3 %>
                            <h1><%= "Community Activity" %> </h1>
                <% else %>
                    <%= "NOT WORKING" %>
                <% end %>
                
                
                
                <!-- Allow user to update the time/date of their activity -->
                <%= form_for([@user,@activity,@week]) do |fw| %>
                <div class="form-group">
                    <%= fw.label :date_completed, "Date completed:"  %></br>
                    <%= fw.date_field :date_completed, class: 'form-control', required: true %>
                </div>
                <%= fw.submit 'Save', class: 'btn btn-primary btn-lg' %>
                <% end %>

                
                
                
                
            </div>
            <%= render 'layouts/footer' %>


    </body>

</html>

app/views/weeks/index.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/bootstrap' %>

    <body style="padding-top: 100px;">

        <%= render 'layouts/header' %>

            <div>
                <!-- Rendering the Type of Activity -->
                <% if $activity_type_var == 1 %>
                    <h1><%= "Personal Activity" %></h1>

                <% elsif $activity_type_var == 2 %>
                    <h1> <%= "Physical Activity" %> </h1>

                <% elsif $activity_type_var == 3 %>
                    <h1><%= "Community Activity" %> </h1>
                
                <% else %>
                    <%= "NOT WORKING" %>
                <% end %>
                
                <h4><%= @activity_name %></h4>
                <h4> Week <%=@week_number %></h4>

                
                <!-- Rendering the Activity Name -->
                <% @weeks.where(activities_id: @activity_id, week_num:@week_number).each do |week| %>
                <h4>Date Completed: <%= week.date_completed %></h4>
                
                <li><%= link_to "Update date", edit_user_activity_week_path(:user_id => @user_id, :activity_id => week.activities_id, :id => week.id, :week_num => @week_number) %></li>     
                <% end %>  
                
                <h4>Status</h4>
                <h5> Submitted: <%=@submitted %></h5>
                <h5> Approved: <%=@approved %></h5>
                
                
            </div>
            <%= render 'layouts/footer' %>


    </body>

</html>

app/views/weeks/new.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/bootstrap' %>

<body style="padding-top: 100px;">

    <%= render 'layouts/header' %>
    
    <div>
        
        <!-- Rendering the Type of Activity -->
        <% if $activity_type_var == 1 %>
                <h1><%= "Personal Activity" %></h1>
        
        <% elsif $activity_type_var == 2 %>
               <h1> <%= "Physical Activity" %> </h1>

        <% elsif $activity_type_var == 3 %>
                <h1><%= "Community Activity" %> </h1>
        <% else %>
                <%= "NOT WORKING" %>      
        <% end %>      
        
        
        <!-- Rendering the Activity Name -->
        <% @activities.where(users_id: current_user.id, activity_type: $activity_type_var).each do |activity| %>
            <h4><%= activity.activity_name %></h4>
            <% end %>
        
        <!-- Rendering the Week Number -->
        <% @weeks.where(week_num: @week_number).each do |activity| %>
        <h4>week_num: <%= week.week_num %></h4>
        <h4>date_completed: <%= week.date_completed %></h4>
        <h4>submitted: <%= week.submitted %></h4>
        <h4>approved: <%= week.approved %></h4>
        
            <% end %>
            


    </div>
    <%= render 'layouts/footer' %>

 
</body>

</html>