config/routes.rb
Rails.application.routes.draw do
    
    get '/sup_home', to: 'supervisors#home', as: :sup_home
    get '/facebook', to: 'social#facebook', as: :facebook
    get '/twitter', to: 'social#twitter', as: :twitter
    get '/website', to: 'social#website', as: :website
    get '/instagram', to: 'social#instagram', as: :instagram
    
    get '/secret', to: 'pages#index', as: :secret
    
    resources :users, only: [:new, :create] do
        resources :activities do
            resources :weeks
        end
    end
        
    get '/sign_up', to: 'users#new', as: :sign_up
    get '/home', to: 'users#home', as: :home
    get '/landing', to: 'users#landing', as: :landing
    root to: 'users#landing'
    
    resources :sessions, only: [:new, :create, :destroy]
    get '/log_in', to: 'sessions#new', as: :log_in
    delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :activities, dependent: :destroy
    has_many :weeks, dependent: :destroy
    authenticates_with_sorcery!
    validates :password, length: { minimum: 3 }
    validates :password, confirmation: true
    validates :email, uniqueness: true, email_format: { message: 'has invalid format' }

    def setPersonal
        $activity_type_var = 1
        return "Personal Activity"
    end
    
    def setPhysical
        $activity_type_var = 2
        return "Physical Activity"
    end
    
    def setCommunity
        $activity_type_var = 3
        return "Community Activity"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :create, :landing]
    def landing
    
    end
    
    def new
      @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        $activity_type_var = 1
      if @user.save
          login(params[:user][:email], params[:user][:password])
          flash[:success] = 'Welcome!'
          #want to send an email to users on registration, giving them instructions for how they login in the future, and a guide on how to             use the app effectively
          #UserMailer.signup_confirmation(@user).deliver
          redirect_to new_user_activity_path(@user)
      else
          render root_path
      end
    end

  private

  def user_params
      params.require(:user).permit(:first_name, :surname, :previous_award, :chosen_award, :email, :password, :password_confirmation, :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/bootstrap' %>

<body style="padding-top: 100px;">

    <%= render 'layouts/header' %>
    
    
    <!-- Grid -->
    <div>
        
        <!-- Row 1 -->
        <div class="row">
            
            <!-- Personal Activity Link -->

            
            <div class="col-sm-2 col-md-2">
                <div class="thumbnail tile tile-medium" style="background-color: #a17d10;">
                    <%= link_to user_activities_path(:user_id => current_user.id, :activity_type => "1"), {style: "color: #FFFFFF"} do %>    
                    <h1 style="font-size: 20px">Personal Activity</h1>
                    <i class="fa-links"></i>
                    <% end %>
                </div>
            </div>
            
            
            <!-- Physical Activity Link -->
            
            
            <div class="col-sm-2 col-md-2">
                <div class="thumbnail tile tile-medium" style="background-color: #a17d10;">
                    <%= link_to user_activities_path(@user, :user_id => current_user.id, :activity_type => "2"), {style: "color: #FFFFFF"} do %>    
                    <h1 style="font-size: 20px">Physical Activity</h1>
                    <i class="fa-links"></i>
                    <% end %>
                </div>
            </div>
        </div>    
        
        <!-- Row 2 -->
        <div class="row">
            <!-- Community Activity Link -->
            
            
            <div class="col-sm-2 col-md-2">
                <div class="thumbnail tile tile-medium" style="background-color: #a17d10;">
                    <%= link_to user_activities_path(:user_id => current_user.id, :activity_type => "3"), {style: "color: #FFFFFF"} do %>    
                    <h1 style="font-size: 20px">Community Activity</h1>
                    <i class="fa-links"></i>
                    <% end %>
                </div>
            </div>
            

            <!-- Adventure Activity Link -->
            <div class="col-sm-2 col-md-2">
                <div class="thumbnail tile tile-medium" style="background-color: #a17d10;">
                    <%= link_to user_activities_path(:user_id => current_user.id, :activity_type => "4"), {style: "color: #FFFFFF"} do %>    
                    <h1 style="font-size: 20px">Adventure Activity</h1>
                    <i class="fa-links"></i>
                    <% end %>
                </div>
            </div>
        </div> 
            
            
            


    </div>
    <%= render 'layouts/footer' %>

 
</body>

</html>

app/views/users/landing.html.erb
<div class="app">
    <%= image_tag 'gaisce.png' %></br></br></br>
    <button type="button" class="btn btn-default btn-block" style="colour:">
        <%= link_to log_in_path do %>
        Login
        <i class="fa-links"></i>
        <% end %>
    </button>
    </br>
    <button type="button" class="btn btn-default btn-block">
        <%= link_to sign_up_path do %>
        Register
        <i class="fa-links"></i>
        <% end %>
    </button>
</div>

app/views/users/new.html.erb
<h1>Registration</h1>

<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :surname %>
    <%= f.text_field :surname, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :previous_award, "If you have undertaken any Gaisce award previously, please select the most recent award below." %>
      <%= f.select(:previous_award, [['None completed', 1],['Bronze Award', 2], ['Silver Award', 3],['Both Bronze & Silver',4]]) %></br>
  </div>
  <div class="form-group">
    <%= f.label :chosen_award, "Select the Gaisce Award you are currently undertaking" %></br> 
    <%= f.select(:chosen_award, [['Bronze Award', 26], ['Silver Award', 52], ['Gold Award', 78]]) %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>