config/routes.rb
Rails.application.routes.draw do
    
    get '/sup_home', to: 'supervisors#home', as: :sup_home
    get '/facebook', to: 'social#facebook', as: :facebook
    get '/twitter', to: 'social#twitter', as: :twitter
    get '/website', to: 'social#website', as: :website
    get '/instagram', to: 'social#instagram', as: :instagram
    
    get '/secret', to: 'pages#index', as: :secret
    
    resources :users, only: [:new, :create] do
        resources :activities do
            resources :weeks
        end
    end
        
    get '/sign_up', to: 'users#new', as: :sign_up
    get '/home', to: 'users#home', as: :home
    get '/landing', to: 'users#landing', as: :landing
    root to: 'users#landing'
    
    resources :sessions, only: [:new, :create, :destroy]
    get '/log_in', to: 'sessions#new', as: :log_in
    delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/models/activity.rb
class Activity < ActiveRecord::Base
    belongs_to :user
    has_many :weeks, dependent: :destroy
    
    $activity_type_var = 1;

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :set_user

    
    def index
        @activities = Activity.all
        
        @activity_type = params[:activity_type]
        
        if @activity_type == "1"
            $activity_type_var = 1
        elsif @activity_type == "2"
            $activity_type_var = 2
        else
            $activity_type_var = 3
        end
        

        #@week = Week.find(params[:activities_id])
        #@week_id = @week.id-1
    end
    
    def new
        @activity = Activity.new
    end
    
    
    def create
        @activity = Activity.new(activity_params)
        if @activity.save
            #UserMailer.activity_added(@user,@activity).deliver
            @chosen_award_user.times do |index|
              Week.create(activities_id: @activity.id, week_num: index+1, date_completed: 2016-01-01, submitted: false, approved: false)
        end 
            
            
            if $activity_type_var == 1
                $activity_type_var = 2
                redirect_to new_user_activity_path(@user)
                
            elsif $activity_type_var == 2
                $activity_type_var = 3
                redirect_to new_user_activity_path(@user)
            else
                redirect_to home_path(@user)
            end
        else
            redirect_to root_path(@user)
        end
    end
    
    private
    
    def activity_params
        params.require(:activity).permit(:users_id, :activity_type, :activity_name, :approver_email)
    end
    
    def set_user
        @user = User.find(params[:user_id])
        @chosen_award_user = @user.chosen_award
    end
    

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.erb
<!DOCTYPE html>
<html>
    <%= render 'layouts/bootstrap' %>

    <body style="padding-top: 100px;">
        <%= render 'layouts/header' %>
        
        <!-- Rendering the Type of Activity -->
        <% if $activity_type_var == 1 %>
                <h1><%= "Personal Activity" %></h1>
        
        <% elsif $activity_type_var == 2 %>
               <h1> <%= "Physical Activity" %> </h1>

        <% elsif $activity_type_var == 3 %>
                <h1><%= "Community Activity" %> </h1>
        <% else %>
                <%= "NOT WORKING" %>      
        <% end %>

            
        <!-- Rendering the Activity Name -->
        <% @activities.where(users_id: current_user.id, activity_type: $activity_type_var).each do |activity| %>
            <h4><%= activity.activity_name %></h4>
            <!-- Current activity_id = @act_id -->
            <% @act_id = activity.id %>
            <% end %>

        
        <!-- Generating the list of weekly entries -->
        <div>
            <% current_user.chosen_award.times do |index| %>
                <% @activities.where(users_id: current_user.id, activity_type: $activity_type_var).each do |activity| %>
                    <li class="list-group-item">
                        <%= link_to "Week #{index + 1}",user_activity_weeks_path(@user, :user_id => current_user.id, :activity_id => activity.id, :activity_type => $activity_type_var, :week_num => index+1) %>  
                    </li>
                <% end %>
            <% end %>
        </div>
        
        
        <%= render 'layouts/footer' %>
    </body>

</html>

app/views/activities/new.html.erb
<% if $activity_type_var==1 %>

    <h1>Step Two</h1>

    Please fill in the details below for your personal Gaisce activity:

    <%= form_for([@user, @activity]) do |af| %>

    <%= af.hidden_field :users_id, value: current_user.id %>
    <%= af.hidden_field :activity_type, value: 1 %>
    <%= af.label :activity_name, "Personal Activity"  %></br>
    <%= af.text_field :activity_name, :placeholder => "e.g. Piano lessons", class: 'form-control' %></br>
    <%= af.label :approver_email, "Personal Activity Supervisor's Email" %></br>
    <%= af.email_field :approver_email, :placeholder =>  "e.g. tesspiano@outlook.com", class: 'form-control' %></br>

    <%= af.submit 'Next step', class: 'btn btn-primary btn-lg' %>
    <% end %>


<% elsif $activity_type_var==2 %>

    <h1>Step Three</h1>

    Please fill in the details below for your physical Gaisce activity:

    <%= form_for([@user, @activity]) do |af| %>

    <%= af.hidden_field :users_id, value: current_user.id %>
    <%= af.hidden_field :activity_type, value: 2 %>
    <%= af.label :activity_name, "Physical Activity"  %></br>
    <%= af.text_field :activity_name, :placeholder => "e.g. Hockey", class: 'form-control' %></br>
    <%= af.label :approver_email, "Physical Activity Supervisor's Email" %></br>
    <%= af.email_field :approver_email, :placeholder =>  "e.g. hockeycoach@outlook.com", class: 'form-control' %></br>

    <%= af.submit 'Next step', class: 'btn btn-primary btn-lg' %>
    <% end %>

<% else %>
    <h1>Final Step</h1>

    Please fill in the details below for your community Gaisce activity:

    <%= form_for([@user, @activity]) do |af| %>

    <%= af.hidden_field :users_id, value: current_user.id %>
    <%= af.hidden_field :activity_type, value: 3 %>
    <%= af.label :activity_name, "Community Activity"  %></br>
    <%= af.text_field :activity_name, :placeholder => "e.g. Volunteering with Age Action", class: 'form-control' %></br>
    <%= af.label :approver_email, "Community Activity Supervisor's Email" %></br>
    <%= af.email_field :approver_email, :placeholder =>  "e.g. ageaction@outlook.com", class: 'form-control' %></br>

    <%= af.submit 'Finish Registration', class: 'btn btn-primary btn-lg' %>
    <% end %>
<% end %>