config/routes.rb
Rails.application.routes.draw do
    
    get '/sup_home', to: 'supervisors#home', as: :sup_home
    get '/facebook', to: 'social#facebook', as: :facebook
    get '/twitter', to: 'social#twitter', as: :twitter
    get '/website', to: 'social#website', as: :website
    get '/instagram', to: 'social#instagram', as: :instagram
    
    get '/secret', to: 'pages#index', as: :secret
    
    resources :users, only: [:new, :create] do
        resources :activities do
            resources :weeks
        end
    end
        
    get '/sign_up', to: 'users#new', as: :sign_up
    get '/home', to: 'users#home', as: :home
    get '/landing', to: 'users#landing', as: :landing
    root to: 'users#landing'
    
    resources :sessions, only: [:new, :create, :destroy]
    get '/log_in', to: 'sessions#new', as: :log_in
    delete '/log_out', to: 'sessions#destroy', as: :log_out
end

app/views/layouts/_bootstrap.html.erb
 <head>
     <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link type="text/css" href="/_beta/css/fontface.css?v=20141007" rel="stylesheet" media="screen" />
    <link type="text/css" href="/_beta/css/mobile-portrait.css?v=20141007" rel="stylesheet" media="screen" />
    <link type="text/css" href="/_beta/css/mobile-landscape.css?v=20141007" rel="stylesheet" media="screen and (min-width: 480px)" />
    <link type="text/css" href="/_beta/css/tablet.css?v=20141007" rel="stylesheet" media="screen and (min-width: 700px)" />
    <link type="text/css" href="/_beta/css/desktop.css?v=20141008" rel="stylesheet" media="screen and (min-width: 960px)" />
    <link type="text/css" href="/_beta/css/all-site-global.css?v=20141007" rel="stylesheet" media="screen" />
    <link type="text/css" href="/_beta/css/new_snow.css?v=5" rel="stylesheet" media="screen" />
    <div class="container">
</head>

app/views/layouts/_footer.html.erb
        <!-- Footer -->
        <div class="navbar navbar-fixed-bottom" style=" height: 60px; bottom: 0; width: 100%; background-color: #FFFFFF">
            <div class="container">
                <p class="text-muted">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="/home">
                                    <span class="fa-stack">
                                        <i class="fa fa-home fa-stack-1x fa-inverse" style="color: #a17d10;"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="/facebook">
                                    <span class="fa-stack">
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse" style="color: #a17d10;"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="/twitter">
                                    <span class="fa-stack">
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse" style="color: #a17d10;"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="/instagram">
                                    <span class="fa-stack">
                                        <i class="fa fa-instagram fa-stack-1x fa-inverse" style="color: #a17d10;"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="/website">
                                    <span class="fa-stack">
                                        <i class="fa fa-info fa-stack-1x fa-inverse" style="color: #a17d10;"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                </p>
        </div>
        </div>
<!-- jQuery -->
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="javascripts/bootstrap.min.js "></script>

<!-- Custom Theme JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-clean-blog/1.0.4/css/clean-blog.min.css "></script>

app/views/layouts/_header.html.erb
        <!-- Header -->
        <nav class="navbar navbar-default navbar-fixed-top" style="margin-top:20px; background-color: #FFFFFF;">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/home">
                        <%= image_tag('gaisce.png', class: 'img-responsive', style: 'height:90%; width:60%;')%>
                        
                    </a>
                    
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="navbar-brand" href="user_home.html"><i class="fa fa-chevron-left fa-stack-1x fa-inverse" style="color: #a17d10; "></i></a>
                        </li>
                        <li><a class="navbar-brand" href="#"><i class="fa fa-bars fa-stack-1x fa-inverse " style="color: #a17d10; margin-left:10%; margin-right:10%"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Gaisce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="navbar">
  <ul class="nav navbar-nav">
    <% if current_user %>
      <li><%= link_to 'Home Page', home_path %></li>
    <% else %>
      <li><%= link_to 'Sign Up', sign_up_path %></li>
      <li><%= link_to 'Log In', log_in_path %></li>
    <% end %>
  </ul>
  <% if current_user %>
    <ul class="nav navbar-nav pull-right">
      <li><span><%= current_user.first_name %></span></li>
      <li><%= link_to 'Log Out', log_out_path, method: :delete %></li>
    </ul>
  <% end %>
</div>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>